import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';
import { db } from './db';
import type { Attendance, Student, Teacher } from './types';
const now=()=>new Date().toISOString(); const id=()=>crypto.randomUUID();
function text(v:unknown){return String(v??'').trim()}
function rows(file:File){return file.arrayBuffer().then(buf=>{let wb:XLSX.WorkBook;try{wb=XLSX.read(buf,{type:'array'});}catch{throw new Error('File Excel tidak dapat dibaca. Gunakan file .xlsx yang valid.')}const sheetName=wb.SheetNames[0];if(!sheetName)throw new Error('File Excel tidak memiliki sheet.');const ws=wb.Sheets[sheetName];const data=XLSX.utils.sheet_to_json<Record<string,unknown>>(ws,{defval:'',range:3});if(!data.length)throw new Error('File Excel tidak berisi data pada baris yang sesuai template.');return data})}
export async function importStudents(file:File){const data=await rows(file);let added=0,updated=0,skipped=0;for(const r of data){const nisn=text(r.NISN),nama=text(r.Nama),kelas=text(r.Kelas),kontak=text(r.Kontak);if(!nisn||!nama||!kelas){skipped++;continue}const old=await db.students.where('nisn').equals(nisn).first();const value:Student={id:old?.id||id(),nisn,nama,kelas,kontak,deleted:0,synced:0,updatedAt:now()};await db.students.put(value);old?updated++:added++}return{added,updated,skipped,total:data.length}}
export async function importTeachers(file:File){const data=await rows(file);let added=0,updated=0,skipped=0;for(const r of data){const nik=text(r.NIK),nama=text(r.Nama),role=text(r.Role).toLowerCase(),kelas=text(r.Kelas),password=text(r.Password);if(!nik||!nama||!password||!['guru','guru bidang','admin'].includes(role)){skipped++;continue}const old=await db.teachers.where('nik').equals(nik).first();const value:Teacher={id:old?.id||id(),nik,nama,role:role as Teacher['role'],kelas:kelas||'SEMUA',password,deleted:0,synced:0,updatedAt:now()};await db.teachers.put(value);old?updated++:added++}return{added,updated,skipped,total:data.length}}
function saveWorkbook(name:string,sheet:string,data:Record<string,unknown>[]){const wb=XLSX.utils.book_new();const ws=XLSX.utils.json_to_sheet(data);ws['!cols']=Object.keys(data[0]||{}).map(k=>({wch:Math.max(14,k.length+3)}));XLSX.utils.book_append_sheet(wb,ws,sheet);const arr=XLSX.write(wb,{bookType:'xlsx',type:'array'});saveAs(new Blob([arr],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),name)}
export async function exportStudents(){const a=(await db.students.filter(x=>!x.deleted).toArray()).sort((x,y)=>x.kelas.localeCompare(y.kelas)||x.nama.localeCompare(y.nama));saveWorkbook(`Data_Siswa_${new Date().toLocaleDateString('en-CA')}.xlsx`,'Data Siswa',a.map((x,i)=>({No:i+1,NISN:x.nisn,Nama:x.nama,Kelas:x.kelas,Kontak:x.kontak})));return a.length}
export async function exportTeachers(){const a=(await db.teachers.filter(x=>!x.deleted).toArray()).sort((x,y)=>x.nama.localeCompare(y.nama));saveWorkbook(`Data_Guru_${new Date().toLocaleDateString('en-CA')}.xlsx`,'Data Guru',a.map((x,i)=>({No:i+1,NIK:x.nik,Nama:x.nama,Role:x.role,Kelas:x.kelas})));return a.length}
function periodStart(end:Date,months:number){const start=new Date(end.getFullYear(),end.getMonth()-(months-1),1);start.setHours(0,0,0,0);return start}
function dateKey(value:Date){return value.toLocaleDateString('en-CA')}
function indonesianDay(value:Date){return['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'][value.getDay()]}
function stamp(value:Date){return{Hari:indonesianDay(value),Tanggal:value.toLocaleDateString('id-ID'),WaktuDownload:value.toLocaleTimeString('id-ID')}}
function summarize(students:Student[],attendance:Attendance[],start:Date,end:Date,downloadedAt:Date){const days=Math.max(1,Math.floor((end.getTime()-start.getTime())/86400000)+1);return students.map((student,index)=>{const records=attendance.filter(row=>row.studentId===student.id&&row.tanggal>=dateKey(start)&&row.tanggal<=dateKey(end));const hadir=records.filter(row=>row.status==='HADIR'||row.status==='TERLAMBAT').length;const terlambat=records.filter(row=>row.status==='TERLAMBAT').length;const sakit=records.filter(row=>row.status==='SAKIT').length;const izin=records.filter(row=>row.status==='IZIN').length;const alpa=records.filter(row=>row.status==='ALPA').length;return{No:index+1,NISN:student.nisn,Nama:student.nama,Kelas:student.kelas,'Hari Periode':days,Hadir:hadir,Terlambat:terlambat,Sakit:sakit,Ijin:izin,Alpa:alpa,'Persentase Kehadiran':`${((hadir/days)*100).toFixed(2)}%`,...stamp(downloadedAt)}})}
export async function exportAttendanceReport(){const students=await db.students.filter(student=>!student.deleted).toArray();const attendance=await db.attendance.toArray();const end=new Date();end.setHours(0,0,0,0);const downloadedAt=new Date();const workbook=XLSX.utils.book_new();const periods=[['Harian',0],['Bulanan',1],['Tiga Bulan',3],['Enam Bulan',6]] as const;for(const[name,months] of periods){const start=months===0?new Date(end):periodStart(end,months);const data=summarize(students,attendance,start,end,downloadedAt);XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet(data),name)}const daily=attendance.filter(row=>row.tanggal===dateKey(end)).map((row,index)=>{const student=students.find(item=>item.id===row.studentId);const attendanceDate=new Date(`${row.tanggal}T00:00:00`);return{No:index+1,NISN:student?.nisn||'',Nama:student?.nama||'',Kelas:student?.kelas||'','Hari Absen':indonesianDay(attendanceDate),'Tanggal Absen':attendanceDate.toLocaleDateString('id-ID'),'Jam Masuk':row.jamMasuk,'Jam Pulang':row.jamPulang||'-',Status:row.status,'Hari Download':indonesianDay(downloadedAt),'Tanggal Download':downloadedAt.toLocaleDateString('id-ID'),'Waktu Download':downloadedAt.toLocaleTimeString('id-ID')}});XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet(daily),'Detail Harian');XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet([{Keterangan:'Cap waktu file diunduh',...stamp(downloadedAt)}]),'Info Export');const array=XLSX.write(workbook,{bookType:'xlsx',type:'array'});saveAs(new Blob([array],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`Rekap_Kehadiran_${dateKey(end)}.xlsx`);return students.length}
export function downloadTemplate(kind:'siswa'|'guru'){const a=document.createElement('a');a.href=`./templates/template-${kind}.xlsx`;a.download=`template-${kind}.xlsx`;a.click()}
